modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "stack_the_cards"
version = "${version}"
displayName = "Stack The Cards"
authors = ""
description = '''

'''
#logoFile = ""
#mixinConfigs = "stackthecards.mixin.json"
[[dependencies.stack_the_cards]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stack_the_cards]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stack_the_cards]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stackthecards.mixins.json"
